version: '3.8'
services:
  proxy:
    build: ./node_proxy
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
